config/routes.rb
Ctaa::Application.routes.draw do
  root :to => "home#index"
  match '/canvas' => "home#canvas", :via => :post

  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout

  # Timeline
  match "/timeline" => "timelines#index", :as => "timeline", :via => :get
    
end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
  validates_presence_of :name
  validates_uniqueness_of :email
  validates_format_of :email, :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    find_by_provider_and_uid(auth["provider"], auth["uid"]) || create_with_omniauth(auth)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :set_layout
  helper_method :current_user
  
  def set_layout
    "application"
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery

  def index
    
  end
  
  def canvas
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "You are now signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You are signed out!"
  end

  def failure
    redirect_to root_url, alert: "Sorry, incorrect email address or password, please try again."
  end
  
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
	protect_from_forgery

	def index
    respond_to do |format|
      format.js { render :json => { :foo => "bar" } }
    end    
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/canvas.html.erb
<div style="text-align:center;margin-top:100px;">
	<h1>ctaa + facebook.  soon.</h1>
</div>

app/views/home/index.html.erb
<div style="text-align:center;margin-top:100px;">
	<% if current_user %>
		<h1>coming soon.</h1>
	<% else %>
		<b>Sign In Using:</b>
		<div style="text-align:center;margin-top:10px;margin-bottom:10px;">
			<%= link_to image_tag("facebook.png"), "/auth/facebook", :title => "Facebook" %>
			<%= link_to image_tag("twitter.png"), "/auth/twitter", :title => "Twitter" %>
		</div>
		<strong>Don't use these services?</strong>
		<%= link_to "Create an account", "/auth/identity/register" %> or

		<div id="login-box" class="modal hide fade">
			<div class="modal-header">
				<a class="close" href="#">×</a>
				<h3>Login</h3>
			</div>
			<%= form_tag "/auth/identity/callback" do %>
			<div class="modal-body">
				<div class="clearfix">
					<label for="email_input">Email Address</label>
					<div class="input">
						<input type="text" size="30" name="auth_key" id="email_input" class="xlarge">
					</div>
				</div>

				<div class="clearfix">
					<label for="password_input">Password</label>
					<div class="input">
						<input type="password" size="30" name="password" id="email_input" class="xlarge">
					</div>
				</div>

			</div>
			<div class="modal-footer">
				<%= submit_tag "Login", :class => "btn primary" %>
			</div>
			<% end %>
		</div>

		<a href="#" data-controls-modal="login-box" data-backdrop="true" data-keyboard="true">login</a>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Camp Tevya Alumni Association</title>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<script>
		$(document).ready(function() {
			$("li.menu").dropdown();
			$(".alert-message").alert();
		});
	</script>
	<link rel="stylesheet" href="http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css">
</head>
<body>

<div class="topbar">
      <div class="fill">
        <div class="container">
          <h3><%= link_to "Camp Tevya Alumni Association", root_path %></h3>
          <ul>
            <li><%= link_to "Home", root_path %></li>
            <li><a href="#" class="coming-soon">About</a></li>
            <li><a href="http://www.camptevya.org" target="NEW">Camp Tevya</a></li>
          </ul>
					<% if current_user %>
          <ul class="nav secondary-nav">
            <li class="menu">
              <a href="#" class="menu"><%= current_user.name %></a>
              <ul class="menu-dropdown">
                <li><a href="#" class="twipsy-link">Profile</a></li>
                <li><a href="#" class="twipsy-link" title="This is a test">Events</a></li>
                <li class="divider"></li>
                <li><%= link_to "Sign Out", signout_path %></li>
              </ul>
            </li>
          </ul>
          <% end %>
        </div>
      </div>
   </div>

<div class="container">
	<div class="content">
		<div class="page-header">
			<h1>Amid Verdant Woodlands <small>...come to the porch, you have a package</small></h1>
		</div>
		<div class="row">
			<div class="span10">
				<% if notice %>
						<div class="alert-message success fade in">
							<a class="close" href="#">×</a>
							<p><%= notice %></p>
						</div>
				<% end %>
				<% if alert %>
						<div class="alert-message error fade in">
							<a class="close" href="#">×</a>
							<p><%= alert %></p>
						</div>
				<% end %>

				<%= yield %>
			</div>
			<div class="span4">
				<h3>Announcements</h3>
			</div>
		</div>
	</div>
	<footer>
		<p>&copy; Camp Tevya Alumni Association 2011</p>
	</footer>
</div>

</body>
</html>